spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.255.129
    port: 5672
    username: admin
    password: admin

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka

#重试
ribbon:
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
  OkToRetryOnAllOperations: true
