spring:
  application:
    name: order-service

server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka, http://127.0.0.1:2002/eureka

feign:
  hystrix:
    enabled: true

#默认是1秒，可以不配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


